### ISSUE TITLE
Usage instruction

### ISSUE THREAD

**Issue by Titukis** [spiritascend/blurlconvert#2]
Hey, how to use this thing? I would like to know. I'm gonna use it to download Jam tracks

**Comment by Samford1** [comment]
hey mate i just built the executable but cant figure out how to use it. would've thought i would just have to drag the json file onto the exe but no luck. sorry to bother

**Comment by calebtb06** [comment]
Did you get it workin?

**Comment by Titukis** [comment]
> Did you get it workin?

Nope, but I found this Telegram group, where you can easily find all multitracks https://t.me/FortniteFestivalStems
